ASM = nasm
CC  = gcc
LD  = ld
CFLAGS = -m32 -ffreestanding -fno-pie -fno-stack-protector -Wall -Wextra -c

all: os-image.bin

os-image.bin: boot.bin kernel.bin
	cat boot.bin kernel.bin > os-image.bin

boot.bin: boot.asm
	$(ASM) boot.asm -f bin -o boot.bin

kernel_entry.o: kernel_entry.asm
	$(ASM) kernel_entry.asm -f elf32 -o kernel_entry.o

kernel.o: kernel.c idt.h
	$(CC) $(CFLAGS) kernel.c -o kernel.o

idt.o: idt.c idt.h
	$(CC) $(CFLAGS) idt.c -o idt.o

isr.o: isr.asm
	$(ASM) isr.asm -f elf32 -o isr.o

kernel.bin: kernel_entry.o idt.o isr.o kernel.o link.ld
	$(LD) -m elf_i386 -T link.ld -o kernel.elf kernel_entry.o idt.o isr.o kernel.o
	objcopy -O binary kernel.elf kernel.bin

run: os-image.bin
	qemu-system-i386 -drive format=raw,file=os-image.bin -serial stdio

clean:
	rm -f *.o *.bin *.elf os-image.bin
